export const FETCH_CATEGORY= "FETCH_CATEGORY";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILED = "FETCH_CATEGORY_FAILED";

export const CREATE_CATEGORY="CREATE_CATEGORY";
export const CREATE_CATEGORY_SUCCESS="CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILED="CREATE_CATEGORY_FAILED";

export const UPDATE_CATEGORY="UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS="UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILED="UPDATE_CATEGORY_FAILED";

export const DELETE_CATEGORY="DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS="DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED="DELETE_CATEGORY_FAILED";

export const GET_CATEGORY_ITEM = "GET_CATEGORY_ITEM";
export const GET_CATEGORY_ITEM_SUCCESS = "GET_CATEGORY_ITEM_SUCCESS";
export const GET_CATEGORY_ITEM_FAILED = "GET_CATEGORY_ITEM_FAILED";