export const FETCH_COLORBIKE = "FETCH_COLORBIKE";
export const FETCH_COLORBIKE_SUCCESS = "FETCH_COLORBIKE_SUCCESS";
export const FETCH_COLORBIKE_FAILED = "FETCH_COLORBIKE_FAILED";

export const CREATE_COLORBIKE="CREATE_COLORBIKE";
export const CREATE_COLORBIKE_SUCCESS="CREATE_COLORBIKE_SUCCESS";
export const CREATE_COLORBIKE_FAILED="CREATE_COLORBIKE_FAILED";

export const UPDATE_COLORBIKE="UPDATE_COLORBIKE";
export const UPDATE_COLORBIKE_SUCCESS="UPDATE_COLORBIKE_SUCCESS";
export const UPDATE_COLORBIKE_FAILED="UPDATE_COLORBIKE_FAILED";

export const DELETE_COLORBIKE="DELETE_COLORBIKE";
export const DELETE_COLORBIKE_SUCCESS="DELETE_COLORBIKE_SUCCESS";
export const DELETE_COLORBIKE_FAILED="DELETE_COLORBIKE_FAILED";

export const GET_COLORBIKE_ITEM = "GET_COLORBIKE_ITEM";
export const GET_COLORBIKE_ITEM_SUCCESS = "GET_COLORBIKE_ITEM_SUCCESS";
export const GET_COLORBIKE_ITEM_FAILED = "GET_COLORBIKE_ITEM_FAILED";