export const FETCH_COUPON = "FETCH_COUPON";
export const FETCH_COUPON_SUCCESS = "FETCH_COUPON_SUCCESS";
export const FETCH_COUPON_FAILED = "FETCH_COUPON_FAILED";

export const CREATE_COUPON="CREATE_COUPON";
export const CREATE_COUPON_SUCCESS="CREATE_COUPON_SUCCESS";
export const CREATE_COUPON_FAILED="CREATE_COUPON_FAILED";

export const UPDATE_COUPON="UPDATE_COUPON";
export const UPDATE_COUPON_SUCCESS="UPDATE_COUPON_SUCCESS";
export const UPDATE_COUPON_FAILED="UPDATE_COUPON_FAILED";

export const DELETE_COUPON="DELETE_COUPON";
export const DELETE_COUPON_SUCCESS="DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_FAILED="DELETE_COUPON_FAILED";

export const GET_COUPON_ITEM = "GET_COUPON_ITEM";
export const GET_COUPON_ITEM_SUCCESS = "GET_COUPON_ITEM_SUCCESS";
export const GET_COUPON_ITEM_FAILED = "GET_COUPON_ITEM_FAILED";