export const FETCH_MANUFACTURER= "FETCH_MANUFACTURER";
export const FETCH_MANUFACTURER_SUCCESS = "FETCH_MANUFACTURER_SUCCESS";
export const FETCH_MANUFACTURER_FAILED = "FETCH_MANUFACTURER_FAILED";

export const CREATE_MANUFACTURER="CREATE_MANUFACTURER";
export const CREATE_MANUFACTURER_SUCCESS="CREATE_MANUFACTURER_SUCCESS";
export const CREATE_MANUFACTURER_FAILED="CREATE_MANUFACTURER_FAILED";

export const UPDATE_MANUFACTURER="UPDATE_MANUFACTURER";
export const UPDATE_MANUFACTURER_SUCCESS="UPDATE_MANUFACTURER_SUCCESS";
export const UPDATE_MANUFACTURER_FAILED="UPDATE_MANUFACTURER_FAILED";

export const DELETE_MANUFACTURER="DELETE_MANUFACTURER";
export const DELETE_MANUFACTURER_SUCCESS="DELETE_MANUFACTURER_SUCCESS";
export const DELETE_MANUFACTURER_FAILED="DELETE_MANUFACTURER_FAILED";

export const GET_MANUFACTURER_ITEM = "GET_MANUFACTURER_ITEM";
export const GET_MANUFACTURER_ITEM_SUCCESS = "GET_MANUFACTURER_ITEM_SUCCESS";
export const GET_MANUFACTURER_ITEM_FAILED = "GET_MANUFACTURER_ITEM_FAILED";