export const FETCH_MODELBIKE= "FETCH_MODELBIKE";
export const FETCH_MODELBIKE_SUCCESS = "FETCH_MODELBIKE_SUCCESS";
export const FETCH_MODELBIKE_FAILED = "FETCH_MODELBIKE_FAILED";

export const CREATE_MODELBIKE="CREATE_MODELBIKE";
export const CREATE_MODELBIKE_SUCCESS="CREATE_MODELBIKE_SUCCESS";
export const CREATE_MODELBIKE_FAILED="CREATE_MODELBIKE_FAILED";

export const UPDATE_MODELBIKE="UPDATE_MODELBIKE";
export const UPDATE_MODELBIKE_SUCCESS="UPDATE_MODELBIKE_SUCCESS";
export const UPDATE_MODELBIKE_FAILED="UPDATE_MODELBIKE_FAILED";

export const DELETE_MODELBIKE="DELETE_MODELBIKE";
export const DELETE_MODELBIKE_SUCCESS="DELETE_MODELBIKE_SUCCESS";
export const DELETE_MODELBIKE_FAILED="DELETE_MODELBIKE_FAILED";

export const GET_MODELBIKE_ITEM = "GET_MODELBIKE_ITEM";
export const GET_MODELBIKE_ITEM_SUCCESS = "GET_MODELBIKE_ITEM_SUCCESS";
export const GET_MODELBIKE_ITEM_FAILED = "GET_MODELBIKE_ITEM_FAILED";