export const FETCH_STORE = "FETCH_STORE";
export const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS";
export const FETCH_STORE_FAILED = "FETCH_STORE_FAILED";

export const CREATE_STORE="CREATE_STORE";
export const CREATE_STORE_SUCCESS="CREATE_STORE_SUCCESS";
export const CREATE_STORE_FAILED="CREATE_STORE_FAILED";

export const UPDATE_STORE="UPDATE_STORE";
export const UPDATE_STORE_SUCCESS="UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAILED="UPDATE_STORE_FAILED";

export const DELETE_STORE="DELETE_STORE";
export const DELETE_STORE_SUCCESS="DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAILED="DELETE_STORE_FAILED";

export const GET_STORE_ITEM = "GET_STORE_ITEM";
export const GET_STORE_ITEM_SUCCESS = "GET_STORE_ITEM_SUCCESS";
export const GET_STORE_ITEM_FAILED = "GET_STORE_ITEM_FAILED";